#!/bin/bash
# auto-generated by resolve-tools.py — host-side rootless build toolchain
export BNASEC_BASE=/home/z/my-project/bnasec-build
export ROOT=/home/z/my-project/bnasec-build/tools-root
export PATH="$ROOT/usr/bin:$ROOT/usr/sbin:$ROOT/sbin:$ROOT/bin:$ROOT/usr/lib/llvm-19/bin:$PATH"
export LD_LIBRARY_PATH="$ROOT/usr/lib/x86_64-linux-gnu/fakechroot:$ROOT/usr/lib/x86_64-linux-gnu/libfakeroot:$ROOT/usr/lib/x86_64-linux-gnu:$ROOT/lib/x86_64-linux-gnu:$ROOT/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PERL5LIB="$ROOT/usr/share/perl5:$ROOT/usr/share/perl5/vendor_perl:$ROOT/usr/lib/x86_64-linux-gnu/perl5/5.40 $ROOT/usr/lib/x86_64-linux-gnu/perl5/5.38 $ROOT/usr/lib/x86_64-linux-gnu/perl5/5.36:$ROOT/usr/lib/x86_64-linux-gnu/perl-base${PERL5LIB:+:$PERL5LIB}"
export PYTHONPATH="$ROOT/usr/lib/python3/dist-packages${PYTHONPATH:+:$PYTHONPATH}"
export GIO_MODULE_DIR="$ROOT/usr/lib/x86_64-linux-gnu/gio/modules"
