#!/usr/bin/env python3
"""BNAsec rootless build toolchain resolver.

Resolves recursive deps of host-side build tools from Debian trixie indexes,
downloads debs in parallel, extracts into tools-root (dpkg -x, rootless),
and writes bnasec-build/tools-env.sh with the right PATH/LD_LIBRARY_PATH.
"""
import concurrent.futures as cf
import gzip
import os
import re
import subprocess
import sys
import urllib.request

BASE = "/home/z/my-project/bnasec-build"
IDX = os.path.join(BASE, "repo-index")
DEBS = os.path.join(BASE, "debs")
TOOLS = os.path.join(BASE, "tools-root")
MIRROR = "http://deb.debian.org/debian"
SUITE = "trixie"
ARCH = "amd64"
COMPS = ["main", "contrib", "non-free", "non-free-firmware"]

# host-side toolchain roots (grub-pc-bin added for hybrid BIOS+UEFI iso)
ROOTS = [
    "mmdebstrap", "arch-test", "xorriso", "mtools", "squashfs-tools",
    "qemu-system-x86", "qemu-utils", "ovmf", "grub-efi-amd64-bin",
    "grub-pc-bin", "file", "fakeroot", "fakechroot", "wget", "cpio",
    "e2fsprogs",
]


def fetch_index(comp: str) -> dict:
    gz = os.path.join(IDX, f"Packages.{comp}.gz")
    url = f"{MIRROR}/dists/{SUITE}/{comp}/binary-{ARCH}/Packages.gz"
    if not os.path.exists(gz):
        print(f"fetch {url}")
        urllib.request.urlretrieve(url, gz)
    pkgs = {}
    with gzip.open(gz, "rt", encoding="utf-8", errors="replace") as fh:
        para, key = {}, None
        for line in fh:
            line = line.rstrip("\n")
            if not line.strip():
                if para.get("Package"):
                    pkgs[para["Package"]] = para
                para, key = {}, None
                continue
            if line[0] in " \t" and key:
                para[key] += "\n" + line.strip()
            elif ":" in line:
                key, _, val = line.partition(":")
                para[key] = val.strip()
        if para.get("Package"):
            pkgs[para["Package"]] = para
    return pkgs


def first_alt(dep: str) -> str:
    s = dep.strip().split("|")[0].strip()
    s = re.sub(r"\s*\([^)]*\)", "", s)
    s = s.split(":")[0].strip()
    return s


def resolve(all_pkgs: dict, roots: list) -> list:
    provides = {}
    for name, d in all_pkgs.items():
        for prov in (d.get("Provides") or "").split(","):
            prov = first_alt(prov)
            if prov:
                provides.setdefault(prov, name)
    seen, order = set(), []
    stack = [first_alt(r) for r in roots]
    while stack:
        name = stack.pop()
        if not name or name in seen:
            continue
        target = name if name in all_pkgs else provides.get(name)
        if not target or target not in all_pkgs or target in seen:
            continue
        seen.add(target)
        order.append(target)
        d = all_pkgs[target]
        for field in ("Pre-Depends", "Depends"):
            for alt in (d.get(field) or "").split(","):
                if alt.strip():
                    stack.append(first_alt(alt))
    return order


def download(pkg: str, all_pkgs: dict):
    fname = all_pkgs[pkg]["Filename"]
    dest = os.path.join(DEBS, os.path.basename(fname))
    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        return dest, 0
    urllib.request.urlretrieve(f"{MIRROR}/{fname}", dest)
    return dest, os.path.getsize(dest)


def main():
    os.makedirs(IDX, exist_ok=True)
    os.makedirs(DEBS, exist_ok=True)
    all_pkgs = {}
    for comp in COMPS:
        all_pkgs.update(fetch_index(comp))
    print(f"index packages: {len(all_pkgs)}")

    order = resolve(all_pkgs, ROOTS)
    print(f"resolved {len(order)} packages")

    total = 0
    with cf.ThreadPoolExecutor(max_workers=10) as ex:
        futs = {ex.submit(download, p, all_pkgs): p for p in order}
        for fut in cf.as_completed(futs):
            _, size = fut.result()
            total += size
    print(f"downloaded {len(order)} debs, {total/1e6:.1f} MB")

    for p in order:
        fname = all_pkgs[p]["Filename"]
        deb = os.path.join(DEBS, os.path.basename(fname))
        subprocess.run(["dpkg", "-x", deb, TOOLS], check=True,
                       stdout=subprocess.DEVNULL)
    print(f"extracted to {TOOLS}")

    perl_dirs = " ".join(
        f"$ROOT/usr/lib/x86_64-linux-gnu/perl5/{v}"
        for v in ("5.40", "5.38", "5.36")
    )
    env = f"""#!/bin/bash
# auto-generated by resolve-tools.py — host-side rootless build toolchain
export BNASEC_BASE={BASE}
export ROOT={TOOLS}
export PATH="$ROOT/usr/bin:$ROOT/usr/sbin:$ROOT/sbin:$ROOT/bin:$ROOT/usr/lib/llvm-19/bin:$PATH"
export LD_LIBRARY_PATH="$ROOT/usr/lib/x86_64-linux-gnu/fakechroot:$ROOT/usr/lib/x86_64-linux-gnu/libfakeroot:$ROOT/usr/lib/x86_64-linux-gnu:$ROOT/lib/x86_64-linux-gnu:$ROOT/usr/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
export PERL5LIB="$ROOT/usr/share/perl5:$ROOT/usr/share/perl5/vendor_perl:{perl_dirs}:$ROOT/usr/lib/x86_64-linux-gnu/perl-base${{PERL5LIB:+:$PERL5LIB}}"
export PYTHONPATH="$ROOT/usr/lib/python3/dist-packages${{PYTHONPATH:+:$PYTHONPATH}}"
export GIO_MODULE_DIR="$ROOT/usr/lib/x86_64-linux-gnu/gio/modules"
"""
    with open(os.path.join(BASE, "tools-env.sh"), "w") as fh:
        fh.write(env)
    print("wrote tools-env.sh")


if __name__ == "__main__":
    sys.exit(main())
